### ISSUE TITLE
Purpose of transpose in RCNN

### ISSUE THREAD

**Issue by jtquisenberry** [jungwhank/rcnn-text-classification-pytorch#2]
On line 26 of `rcnn-text-classification-pytorch/model.py `, function `transpose` is used. 

```
output = self.tanh(self.W(output)).transpose(1, 2)
```

Could you please explain why it is necessary or useful to transpose this tensor?

**Comment by jungwhank** [comment]
Hi, @jtquisenberry 

I tranposed it because of `F.max_pool1d` layer.
https://pytorch.org/docs/stable/generated/torch.nn.MaxPool1d.html
As you can see in document above, input shape is `(N, C, L_in)` and output shape is `(N, C, L_out)`.

More details, `equation (5)` in paper,
>The pooling layer converts texts with various lengths into a fixed-length vector. With the pooling layer, we can capture
the information throughout the entire text.

It means that we should pooling the sequence length dimension. So, we should transpose seq_len dimension to last dimension before using maxpooling layer (See the dimension change below). 
https://github.com/jungwhank/rcnn-text-classification-pytorch/blob/aed84f66514322745c4ae004fc3cff772d6f1c0c/model.py#L26-L29

I hope it helps.
Thanks

**Comment by jtquisenberry** [comment]
Thank you, @jungwhank , that explanation helps.

For others who may not know,

* N = batch size / sample size
* C = the number of features / channels / filters
* L = sequence length
